### ISSUE TITLE
How to speed up Family Finding with process_kmer_to_graph.py? 

### ISSUE THREAD

**Issue by 52teth** [Magdoll/Cogent#10]
Dear Cogent developer,
Thanks for  Cogent which makes recontruct the contig for each gene possible.  
Recently I have test Cogent with my isoseq data. But when I use  process_kmer_to_graph.py to do the 'Family Finding', it really spends too much time and memory.  I have tracked my  process_kmer_to_graph.py process and found that it only took one cpu. So I wonder if there any way to speed up the 'Family Finding' with multiple cpus?

Many thanks for your reply!

**Comment by Magdoll** [comment]
Hi,
I am aware of this issue and working on an alternative way to identify gene families. I hope to release it in a week or two. I'll post to this issue and update the repo when it's ready!

Thanks,
--Liz

**Comment by 52teth** [comment]
@Magdoll  Thanks a lot！Look forward to your new version of the release！

**Comment by Magdoll** [comment]
Hi @52teth ,

Cogent version 2.0 has just been pushed to GitHub.

You will need to install the new version and additionally, follow instructions [here](https://github.com/Magdoll/Cogent/wiki/Installing-Cogent#cupcake) for installing minimap and Cupcake.

Afterwards, you can follow the [tutorial on family finding for big datasets](https://github.com/Magdoll/Cogent/wiki/Running-Cogent#findbig).

This is still experimental, so please let me know how it goes. 

Thanks,
--Liz

**Comment by 52teth** [comment]
@Magdoll  Thanks a lot! I  will try it with my Isoseq data!
