### ISSUE TITLE
Cogent_family_finding_issue

### ISSUE THREAD

**Issue by yangtrytry** [Magdoll/Cogent#17]
hi，dear:
I used tens of thousands of pieces of data, after Cogent_family_finding, some of the sequences in the preCluster_out.orphans.fasta and preCluster_out.chimeras.fasta files and a part in the in.fa file for each of the divided gene families,  however, all sequences of these files  is not equal with my input sequence , and lacking of part of the sequence.why does this happen? In which file is the missing sequence? Please let me know and appreciate!

**Comment by Magdoll** [comment]
Hi @yangtrytry ,

All sequences should be accounted for. Please check `preCluster.output.csv` to see which sequences are assigned to which cluster or is an orphan or chimera. If you notice issues, please give me a specific example of a sequence that is denoted in `preCluster.output.csv` and missing in where it should be.

--Liz

**Comment by yangtrytry** [comment]
Hi,dear,
As you said, all the sequences are indeed in the preCluster.output.csv file, and they are divided into different cluster, such as i5_LQ_taxus_c8842 / f1p1 / 5266, 9571 i1_LQ_taxus_c29820 / f1p0 / 1136, 9571 i0_LQ_taxus_c3243 / f1p0 / 1129 , 9571, these three sequences will be divided into 9571_0 cluster; however, preCluster_out does not contain 9571_0 cluster, and cmd.sh does not involve 9571_0 cluster, which is why, I feel very puzzled and look forward to your reply.

**Comment by Magdoll** [comment]
Hi @yangtrytry ,

Sorry for the late reply (was away during holidays).

Is this still an issue?

Can you please show me the entries containing cluster `9571_0` in `preCluster.output.csv`? Then, can you show me a few sequence IDs from the input file?

I'm wondering if sequence ID format is the issue here. If it is a sequence ID problem, I can fix it pretty quickly, but I need to see what the sequence IDs look like.

--Liz

**Comment by Magdoll** [comment]
Closed unless further information is provided.

**Comment by alissawilliams** [comment]
I am having a similar issue. The original transcriptome I put in has 65,642 sequences, but preCluster.output.csv has 65,614 entries. 

Thanks!

**Comment by Magdoll** [comment]
Hi @alissawilliams ,

I can probably look at this eventually but unfortunately not soon due to the area I'm living in is shutdown w covid19 and i'm prioritizing work in other areas.

Can you elaborate how this would impact downstream analysis?

-Liz

**Comment by alissawilliams** [comment]
Hi Liz-

No problem. Thanks for the reply! I mainly just have a few questions about what's happening to the sequences:

I started with 65,642 sequences. 
In final_partition.txt, there are 45,544. 
In unassigned.fasta, there are 2,107.
In preCluster_out.tucked.fasta, there are 14,244. 
In preCluster_out.orphans.fasta, there are 3,719. 
In preCluster_out.chimeras.fasta, there are 0. 

So in total, between all of the output files, there are 65,614 sequences. This is the same number that are listed in preCluster.output.csv. My first question is related to this number: where did the other 28 sequences go?

My second question is about what the different output files actually are. I know that unassigned reads weren't close enough to any other transcripts to use in family finding, and I know that chimeric reads are sequencing artifacts that shouldn't be used in further steps. However, I don't know what the orphan and tucked sequences are. Would it make sense to include them in constructing the "fake" genome? What criteria led to them being assigned to those groups? 

Thanks!
Alissa

**Comment by monicabritton** [comment]
I am also curious what the meaning of "tucked" is.  Similar to other users, 35% of my input sequences are assigned as "tucked", but I cannot find "tuck" or "tucked" in the github wiki or in the draft MS.  Can you explain what this means? ... thanks ...
