### ISSUE TITLE
Count file from Cogent' test_data folder

### ISSUE THREAD

**Issue by rrim** [Magdoll/Cogent#21]
Hi, I am trying to collapse redundant sequences for a set of full-length transcripts (that has a pretty crappy genome). I decided to use Cogent to collapse the redundant isoforms de novo. But before I use it on my transcripts, I  tried running Cogent using the provided test data. Can you please tell me where test_human.weights file originates from? How do I create similar count file  for my own data? Thanks.

**Comment by Magdoll** [comment]
Hi @rrim,

The `.weights` file is optional. It should contain some count or weighted evidence information about each sequence. For example, it could be the number of full-length reads that support this sequence. 

If weight file is not given, a fake weight file where every sequence has a weight of 1 will be created.

**Comment by rrim** [comment]
Hi @Magdoll ,

Thanks for your reply. 

The reason I asked about the weight file is that whenever I tried using the provided human test data without including the file (during run-Mash process; I used the following command: 
process_kmer_to_graph.py test_human.fa test_human.fa.s1000k30.dist test_human/ human), the downstream reconstruction_contig.py execution on one of the folder failed with the following error message:

> IOError: [Errno 2] No such file or directory: '/mnt/shared/scratch/ab42303/local_apps/Cogent/test_data/test_human/2/hello.log' 

So I am a bit confused how would a fake weight file be created if it is not provided.

**Comment by Magdoll** [comment]
Hi @rrim ,

When you run the test fasta without weights, the scripts will automatically generate `in.weights` for you.

For example:

```
$ mkdir test
$ cd test/
$ cp <path_to>/test_human.fa .
$ run_mash.py -k 30 --cpus=12 test_human.fa
$ process_kmer_to_graph.py test_human.fa test_human.fa.s1000k30.dist test_human/ human
$ tree test_human/

test_human
├── human_0
│   ├── in.fa
│   └── in.weights
└── human_2
    ├── in.fa
    └── in.weights

```

**Comment by Magdoll** [comment]
Also, please note I've recently updated Cogent to work exclusively with minimap2 and removed all usages of GMAP. This is now [Cogent v3.1](https://github.com/Magdoll/Cogent/tree/v3.1). I've also just updated the [wiki](https://github.com/Magdoll/Cogent/wiki/Running-Cogent) to update the run parameters for the scripts.

--Liz

**Comment by rrim** [comment]
Ok, thanks. Will re-try with the latest version

**Comment by rrim** [comment]
Hi, 
I was trying to update COgent to its current version (Cogent 3.1). The installation went on smoothly (as per tutorial). All related scripts were located in my dedicated anaCogent python 2.7 virualenv. All dependencies (minimap2, cDNA_cupcake and Mash were also installed successfully previously). All necessary path variables were already specified.  However, when I entered `run_mash.py --version `command, I got the following error:

`Traceback (most recent call last):
  File "/mnt/shared/scratch/synology/ab42303/apps/conda/envs/anaCogent/bin/run_mash.py", line 4, in <module>
    __import__('pkg_resources').run_script('Cogent==3.1', 'run_mash.py')
  File "/home/ab42303/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/ab42303/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1486, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'run_mash.py'
`
Can you please advice what went wrong here? Thanks.

**Comment by Magdoll** [comment]
Hi @rrim ,

Can you make sure there are no older versions of Cogent in the anaCogent env?

You can check via:
```
$ ls /mnt/shared/scratch/synology/ab42303/apps/conda/envs/anaCogent/lib/python2.7/site-packages/Cogent*
```

You will want to remove any Cogent install that isn't `Cogent-3.1-py2.7.egg`. 

The import message is also strange. It should be importing from the anaCogent env as below:


```
>>> __import__('pkg_resources')
<module 'pkg_resources' from '/mnt/shared/scratch/synology/ab42303/apps/conda/envs/anaCogent/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py'>
```

But instead your err msg shows the import is coming from `/home/ab42303/.local/lib/python2.7/site-packages/pkg_resources/`.
