### ISSUE TITLE
Error in running `process_kmer_to_graph.py`

### ISSUE THREAD

**Issue by ClearloveMiao** [Magdoll/Cogent#27]
Hi, @Magdoll ,

I am running the `process_kmer_to_graph.py` for 'running Family Finding for a small dataset', but it reported such error like the below picture and stopped.

![image](https://user-images.githubusercontent.com/37678675/38967773-23c64c9a-43bb-11e8-9bdf-a814aab2e1f1.png)

It seems like the version of package `six` is too old, but I have installed `six=1.10.0` by using `conda install in anaCogent six=1.10.0`, and it also show success for installing `six=1.10.0`.

So I don't know how to deal with this error. Thanks for any suggestions!

**Comment by ClearloveMiao** [comment]
And what is this error `ImportError: cannot import name xrange` meaning? Is `xrange` a python package?
The error is liking below:
![image](https://user-images.githubusercontent.com/37678675/38993301-ccebede8-4415-11e8-85d4-4be3fd03ae0d.png)

**Comment by Magdoll** [comment]
Hi @ClearloveMiao ,

All of these errors are indicating you are using very different versions of Python and other associated packages. 

I'm going to have you try this. Please edit `setup.py` in your Cogent directory and change the part that contains `setup(name...`  to:

```
setup(name='Cogent',
      version=version,
      description='COding GENome reconstruction Tool using transcript sequences',
      author='Elizabeth Tseng',
      author_email='etseng@pacb.com',
      install_requires=[
          'numpy',
          'networkx==1.10',
          'scikit-image>=0.11.3',
          'pulp',
          'biopython',
          'bx-python==0.7.3'
      ],
      packages=['Cogent', 'Cogent.test'],
      package_dir = {'Cogent':'Cogent'},
      zip_safe=False,
      test_suite = "Cogent.test.test_cogent",
      scripts=['Cogent/run_mash.py',
               'Cogent/process_kmer_to_graph.py',
               'Cogent/gff3_to_collapsed.py',
               'Cogent/reconstruct_contig.py',
               'Cogent/generate_batch_cmd_for_Cogent_reconstruction.py',
               'Cogent/generate_batch_cmd_for_Cogent_family_finding.py'
     ])
```

Then re-build and install. Let me know how it goes.

--liz

**Comment by ClearloveMiao** [comment]
Hi, @Magdoll ,

I have changed the script `setup.py` according to your suggestion, but when I run the `python setup.py install`, it have reported many `warn` when the script was running, because it reported too many and too fast so I haven't copy it at time.

But, after finishing install, what it has showed just like the below picture:
![image](https://user-images.githubusercontent.com/37678675/39028346-c51abf72-4488-11e8-9637-7b672c3d5b6a.png)

So, dose this picture showed proved `Cogent` installed successfully?

However, when I run the `process_kmer_to_graph.py`, it also reported the same error:`ImportError: cannot import name xrange`. Just like the below picture.

![image](https://user-images.githubusercontent.com/37678675/39028589-f7d06434-4489-11e8-9fd2-76d8413fbba4.png)

Thanks for any suggestions!

**Comment by Magdoll** [comment]
Hi @ClearloveMiao 

I'm not sure why scipy is complaining. Please confirm that you are running Python2:

```
(anaCogent) $ which python
/home/anaconda2/envs/anaCogent/bin/python
(anaCogent) $ python --version
Python 2.7.13 :: Anaconda 2.4.1 (64-bit)
```

And also let me know which scipy version you have:

```
(anaCogent) $ python -c "import scipy; print scipy.__version__"
0.17.0
```

**Comment by ClearloveMiao** [comment]
Hi, @Magdoll ,
First, I have confirmed that I am running Python2:

![image](https://user-images.githubusercontent.com/37678675/39079302-1c837076-454a-11e8-9da0-032177b050ef.png)

Second, scipy version I have:

![image](https://user-images.githubusercontent.com/37678675/39079319-6df9d9b8-454a-11e8-9faf-818041491ffa.png)

Thanks for any suggestions!

**Comment by Magdoll** [comment]
Hi @ClearloveMiao ,
It looks like the newer versions of scipy have changed certain libraries. For the meantime, please downgrade scipy to 0.17.0.

--Liz

**Comment by ClearloveMiao** [comment]
Hi, @Magdoll ,

I have downgrade scipy to 0.17.0 by `conda install -n anaCogent scipy=0.17.0`, but when I run `process_kmer_to_graph.py`again, it reported another error:

![image](https://user-images.githubusercontent.com/37678675/39169450-716b7eee-47ca-11e8-9e9e-40207d149f0d.png)

So, what has caused this error and how can I do?

**Comment by Magdoll** [comment]
Closed unless further information is provided.
