### ISSUE TITLE
Errors in the final step : filter_away_subset.py

### ISSUE THREAD

**Issue by ClearloveMiao** [Magdoll/Cogent#29]
When I run the `filter_away_subset.py`, and it has reported such error like below:

![image](https://user-images.githubusercontent.com/37678675/39684015-97c248f4-51eb-11e8-9a01-e9c946d2227e.png)

But it haven't produce `cu_hq.fasta.no5merge.collapsed.rep.fq`in the last step, and it has produced `cu_hq.fasta.no5merge.collapsed.rep.fa`, so I feel very confused about this.

**Comment by Magdoll** [comment]
Hi @ClearloveMiao ,

This is the wrong repo for this question. You should file this at the [Cupcake repo](http://github.com/Magdoll/cDNA_Cupcake).

The error comes from you probably having provided only FASTA, and not FASTQ, for the collapse step. You can convert the fasta into fastq using [fa2fq.py](https://github.com/Magdoll/cDNA_Cupcake/wiki/Sequence-Manipulation-Wiki#convert) in Cupcake. The output will have a `.fastq` suffix nd you can rename it to a `.fq` suffix before you call `filter_away_subset.py` again.

--Liz

**Comment by rnett42** [comment]
I have actually run into the same issue. The directions in this wiki (Tutorial: Using Cogent to collapse redundant transcripts in absence of genome) specify for the use of `hq_isoforms.fasta`

Is the `filter_away_subset.py` step the only one that needs a fastq file of the hq_isoforms?

**Comment by ClearloveMiao** [comment]
@rnett42 Yes, I think it is the only one that needs a fastq file.

**Comment by Magdoll** [comment]
Yes it needs the fastq file. My original response has directions for how to create the fastq from a fasta.

--Liz
