### ISSUE TITLE
Could not finish two failed jobs in the reconstruction step

### ISSUE THREAD

**Issue by jayceejiao** [Magdoll/Cogent#32]
Hi Magdoll,

I am using Cogen 3.3 to reconstruct the coding region for a species without a reference genome. I have finished the "Family Finding" step and have run the reconstruct_contig.py script for each family. Some of the families were first failed but late completed with the suggested parameters "reconstruct_contig.py --nx_cycle_detection -k 60 .". However, I could not get results from two of the failed families with k=60 or larger (120). The scripts have been running for ~ 20h. Attached are the log files from one failed family. Can you help me with this problem?

Thanks!

Chen

[hello.log](https://github.com/Magdoll/Cogent/files/1999121/hello.log)

[nohup.txt](https://github.com/Magdoll/Cogent/files/1999122/nohup.txt)

**Comment by Magdoll** [comment]
Hi @jayceejiao ,

It looks like a coding error on my part that caused it to stay in an infinite loop. However I still need to fix the fundamental issue that is this input data seems very cyclic.

Would it be possible to share the data ("in.fa") with me? Please give me an email address and I'll request a data upload.

--Liz

**Comment by jayceejiao** [comment]
Hi Liz,

Yes, I can send you the two failed sequences. My email address is cj334@cornell.edu.

Thanks!

Chen

**Comment by Magdoll** [comment]
Hi @jayceejiao ,

A request has been emailed.

**Comment by Magdoll** [comment]
Hi,
A fix has been updated for v3.4 at the repo. 
I've also emailed you the Cogent output for the two failed data. 

Please confirm this fixes the issues.

--Liz

**Comment by jayceejiao** [comment]
Hi Liz,

I used git clone https://github.com/Magdoll/Cogent.git to reinstall Cogent. After the installation, my Cogent is still v3.3 and could not finish those two jobs. How can I install v3.4?

Best,

Chen

**Comment by Magdoll** [comment]
Hi @jayceejiao ,
I found that the v3.4, while fixes the problem, produces less optimal results (more # of reconstructed contigs). I'm going to work on fixing that and will let you know how to download the latest version when I have a fix.
--Liz

**Comment by Magdoll** [comment]
Hi @jayceejiao ,

Version 3.5 should have this fixed. Please try it out and confirm.

--Liz

**Comment by jayceejiao** [comment]
Hi @Magdoll,

I have reinstalled the Cogent 3.5 through git clone. I have tried using this command "reconstruct_contig.py (Cogent 3.5) --nx_cycle_detection -k 60 . " for those two failed jobs, I still get the similar message (hello.log) : 

> 2018-05-22 14:55:04,116 - Cogent - INFO - Setting k-mer size to: 60
> 2018-05-22 14:55:04,117 - Cogent - INFO - Setting expected error rate to: 1%
> 2018-05-22 14:55:04,995 - Cogent.splice_cycle - INFO - K-mer in-seq cycle detection: 782 in-seq cycle found with max common         sequence analysis showing min: 61, max: 763, mean: 378.072890026
> 2018-05-22 14:55:05,005 - Cogent - INFO - Adjusting k-mer size to: 100
> 2018-05-22 14:55:09,528 - Cogent - INFO - Doing nx.cycle_detection....
> 2018-05-22 14:55:09,577 - Cogent - INFO - Trying to raise k=120. Rerun attempt.
> 2018-05-22 14:55:10,332 - Cogent.splice_cycle - INFO - K-mer in-seq cycle detection: 664 in-seq cycle found with max common         sequence analysis showing min: 121, max: 784, mean: 452.5
> 2018-05-22 14:55:10,343 - Cogent - INFO - Adjusting k-mer size to: 100
> 2018-05-22 14:55:14,891 - Cogent - INFO - Doing nx.cycle_detection....
> 2018-05-22 14:55:14,946 - Cogent - INFO - Trying to raise k=120. Rerun attempt.
> 2018-05-22 14:55:15,704 - Cogent.splice_cycle - INFO - K-mer in-seq cycle detection: 664 in-seq cycle found with max common         sequence analysis showing min: 121, max: 784, mean: 452.5
> 2018-05-22 14:55:15,714 - Cogent - INFO - Adjusting k-mer size to: 100
> 2018-05-22 14:55:20,206 - Cogent - INFO - Doing nx.cycle_detection....
> 2018-05-22 14:55:20,259 - Cogent - INFO - Trying to raise k=120. Rerun attempt.
> 2018-05-22 14:55:21,240 - Cogent.splice_cycle - INFO - K-mer in-seq cycle detection: 664 in-seq cycle found with max common         sequence analysis showing min: 121, max: 784, mean: 452.5
> 2018-05-22 14:55:21,250 - Cogent - INFO - Adjusting k-mer size to: 100
> 2018-05-22 14:55:25,694 - Cogent - INFO - Doing nx.cycle_detection....
> 2018-05-22 14:55:25,744 - Cogent - INFO - Trying to raise k=120. Rerun attempt.
> 2018-05-22 14:55:26,581 - Cogent.splice_cycle - INFO - K-mer in-seq cycle detection: 664 in-seq cycle found with max common         sequence analysis showing min: 121, max: 784, mean: 452.5
> 2018-05-22 14:55:26,591 - Cogent - INFO - Adjusting k-mer size to: 100
> 2018-05-22 14:55:31,137 - Cogent - INFO - Doing nx.cycle_detection....
> 2018-05-22 14:55:31,191 - Cogent - INFO - Trying to raise k=120. Rerun attempt.
Should I use Cogent 3.5 from the very beginning? 

Thanks!

Chen

**Comment by Magdoll** [comment]
Hi @jayceejiao ,

Please first confirm you are running Cogent 3.5 and also run reconstruct without specifying the kmer_size.  

```
$ python -c "import Cogent; print Cogent.__version__"
3.5

$ reconstruct_contig.py .
```

**Comment by jayceejiao** [comment]
Hi @Magdoll ,

Yes, I am using Cogent 3.5. Now I have fixed the problem by running "reconstruct_contig.py .".

Thanks.

Chen
