### ISSUE TITLE
Cogent reconstruction failed due to sequences containing N

### ISSUE THREAD

**Issue by rrim** [Magdoll/Cogent#34]
Hi,
reconstruct_contig.py complained when sequences in in.fa in the pre-cluster bin contain non A/C/T/G characters. Should these ambiguous nucleotides be removed before running reconstruct_contig.py? But what should we do if the N(s) is/are located in the ORF region? Is there anyway to go about this?
Thanks.

**Comment by Magdoll** [comment]
Hi @rrim ,
Currently Cogent does not accept non A/T/C/G characters. You may either remove them or replace all of them with one of the characters (such as replacing all "N"s with "A"s). 

As far as I know, PacBio Iso-Seq data does not contain Ns. This would be a non PacBio data I presume?

--Liz

**Comment by rrim** [comment]
Thanks for the information.
Yes, you are right. I combined transcripts from Isoseq and RNAseq (assembled _de novo_) data and trying to remove the redundancy of the merged transcripts. The Ns must be originated from RNAseq data, then.
