### ISSUE TITLE
Fail to build Cogent via pitchfork

### ISSUE THREAD

**Issue by aksenia** [Magdoll/Cogent#35]
/usr/local/src/cogent/pitchfork> make Cogent
# No do-clean rule here.
make -j1 -C ports/python/virtualenv do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/python/virtualenv'
/usr/local/apps/python-2.7.11/bin/python
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/python/virtualenv'
make -j1 -C ports/python/pip do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/python/pip'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/python/pip'
make -j1 -C ports/python/cython do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/python/cython'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/python/cython'
make -C ports/thirdparty/openblas do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/thirdparty/openblas'
rm -rf /usr/local/src/cogent/pitchfork/staging/OpenBLAS
mkdir -p /usr/local/src/cogent/pitchfork/staging/OpenBLAS/lib
rsync -avx /usr/local/apps/R-OpenBLAS/lib/libopenblas* /usr/local/src/cogent/pitchfork/staging/OpenBLAS/lib/
sending incremental file list
libopenblas.a -> libopenblas_penrynp-r0.2.10.a
libopenblas.so -> libopenblas_penrynp-r0.2.10.so
libopenblas.so.0 -> libopenblas_penrynp-r0.2.10.so
libopenblas_penrynp-r0.2.10.a
libopenblas_penrynp-r0.2.10.so

sent 37,069,812 bytes  received 63 bytes  24,713,250.00 bytes/sec
total size is 37,060,541  speedup is 1.00
cd /usr/local/src/cogent/pitchfork/staging/OpenBLAS && tar cf - * | tar xf - -C /usr/local/apps/cogent
find /usr/local/src/cogent/pitchfork/staging/OpenBLAS ! -type d|awk -F '/usr/local/src/cogent/pitchfork/staging/OpenBLAS/' '{print $2}' > /usr/local/apps/cogent/var/pkg/OpenBLAS
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/thirdparty/openblas'
make -j1 -C ports/python/numpy do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/python/numpy'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/python/numpy'
make -j1 -C ports/python/scipy do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/python/scipy'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/python/scipy'
make -j1 -C ports/python/decorator do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/python/decorator'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/python/decorator'
make -C ports/thirdparty/zlib do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/thirdparty/zlib'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/thirdparty/zlib'
make -C ports/thirdparty/libpng do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/thirdparty/libpng'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/thirdparty/libpng'
make -j1 -C ports/python/pytz do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/python/pytz'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/python/pytz'
make -j1 -C ports/python/six do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/python/six'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/python/six'
make -j1 -C ports/python/pyparsing do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/python/pyparsing'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/python/pyparsing'
make -j1 -C ports/python/python-dateutil do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/python/python-dateutil'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/python/python-dateutil'
make -j1 -C ports/python/cycler do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/python/cycler'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/python/cycler'
make -j1 -C ports/python/matplotlib do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/python/matplotlib'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/python/matplotlib'
make -j1 -C ports/python/networkx do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/python/networkx'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/python/networkx'
make -j1 -C ports/python/pillow do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/python/pillow'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/python/pillow'
make -j1 -C ports/python/scikit-image do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/python/scikit-image'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/python/scikit-image'
make -j1 -C ports/python/biopython do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/python/biopython'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/python/biopython'
make -j1 -C ports/python/bx-python do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/python/bx-python'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/python/bx-python'
make -j1 -C ports/python/PuLP do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/python/PuLP'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/python/PuLP'
make -C ports/thirdparty/ssw_lib do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/thirdparty/ssw_lib'
make -C /usr/local/src/cogent/pitchfork/workspace/ssw_lib/src CC="gcc  -fPIC -I/usr/local/apps/cogent/include -D_GNU_SOURCE -L/usr/local/apps/cogent/lib -L/usr/local/apps/cogent/lib64 -static-libstdc++" CXX="g++  -fPIC -I/usr/local/apps/cogent/include -D_GNU_SOURCE  -fPIC -I/usr/local/apps/cogent/include -D_GNU_SOURCE -fPIC -I/usr/local/apps/cogent/include -D_GNU_SOURCE -L/usr/local/apps/cogent/lib -L/usr/local/apps/cogent/lib64 -static-libstdc++"
make[2]: Entering directory '/usr/local/src/cogent/pitchfork/workspace/ssw_lib/src'
make[2]: Nothing to be done for 'default'.
make[2]: Leaving directory '/usr/local/src/cogent/pitchfork/workspace/ssw_lib/src'
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/thirdparty/ssw_lib'
make -C ports/thirdparty/mash do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/thirdparty/mash'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/thirdparty/mash'
make -C ports/pacbio/Cogent do-install
make[1]: Entering directory '/usr/local/src/cogent/pitchfork/ports/pacbio/Cogent'
Makefile:18: *** recipe commences before first target.  Stop.
make[1]: Leaving directory '/usr/local/src/cogent/pitchfork/ports/pacbio/Cogent'
Makefile:420: recipe for target 'Cogent' failed
make: *** [Cogent] Error 2

**Comment by Magdoll** [comment]
Hi @aksenia ,

The pitchfork support for Cogent is probably not up to date. I'll contact the pitchfork developer. In the meantime, you should be able to just install Cogent in the pitchfork environment via simply `setup.py`:

https://github.com/Magdoll/Cogent/wiki/Installing-Cogent#installing--cupcake
```
$ cd Cogent
$ python setup.py build
$ python setup.py install
```

Let me know how it goes.
--Liz

**Comment by mjhsieh** [comment]
The makefile error is interesting. @aksenia can you let me know what flavor/version of linux were you using? Thanks! (yes we are phasing out pitchfork, but I still want to know how to reproduce it.)

**Comment by aksenia** [comment]
Dear Liz & Mengjuei,

Thank you for the rapid response! I will try the suggestion above and see what happens. 
Our institute’s system is: openSUSE 13.2 (Harlequin) (x86_64).

**Comment by aksenia** [comment]
Dear  Liz & Mengjuei,

I (or rather our admin with root access) was able to install cogent following your recipe. However during the installation several package version conflicts were reported:
```

 cogent 3.3 has requirement bx-python==0.7.3, but you'll have bx-python 0.8.1 which is incompatible.
cogent 3.3 has requirement networkx==1.10, but you'll have networkx 1.9.1 which is incompatible.
pulp 1.6.8 has requirement pyparsing>=2.0.1, but you'll have pyparsing 1.5.7 which is incompatible.
cupcake 5.3 has requirement bx-python==0.7.3, but you'll have bx-python 0.8.1 which is incompatible.
Installing collected packages: scipy, PyWavelets, pillow, scikit-image, funcsigs, pbr, mock
  Found existing installation: scipy 0.10.0
    Uninstalling scipy-0.10.0:
      Successfully uninstalled scipy-0.10.0
Successfully installed PyWavelets-0.5.2 funcsigs-1.0.2 mock-2.0.0 pbr-4.0.3 pillow-5.1.0 scikit-image-0.13.1 scipy-1.1.0
```
Later on in the setup.py test it fired back:

```
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    'Cogent/generate_batch_cmd_for_Cogent_family_finding.py'
  File "/usr/local/apps/python-2.7.11/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/apps/python-2.7.11/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/apps/python-2.7.11/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/kselav/bin/pitchfolk_installed/lib/python2.7/site-packages/setuptools/command/test.py", line 199, in run
    installed_dists = self.install_dists(self.distribution)
  File "/home/kselav/bin/pitchfolk_installed/lib/python2.7/site-packages/setuptools/command/test.py", line 194, in install_dists
    ir_d = dist.fetch_build_eggs(dist.install_requires or [])
  File "/home/kselav/bin/pitchfolk_installed/lib/python2.7/site-packages/setuptools/dist.py", line 372, in fetch_build_eggs
    replace_conflicting=True,
  File "/home/kselav/bin/pitchfolk_installed/lib/python2.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/home/kselav/bin/pitchfolk_installed/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1111, in best_match
    dist = working_set.find(req)
  File "/home/kselav/bin/pitchfolk_installed/lib/python2.7/site-packages/pkg_resources/__init__.py", line 715, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (networkx 1.9.1 (/home/kselav/bin/pitchfolk_installed/lib/python2.7/site-packages), Requirement.parse('networkx==1.10'))
k
```

**Comment by mhsieh** [comment]
Should be resolved in -  https://github.com/PacificBiosciences/pitchfork/commit/e59ae2cb00c1b986d4525678731324ac9ecb9eec

**Comment by aksenia** [comment]
```
rsync -aKx
/usr/local/src/cogent/pitchfork/staging/pillow-3.4.2//usr/local/apps/cogent/
/usr/local/apps/cogent/
cd
/usr/local/src/cogent/pitchfork/staging/pillow-3.4.2/usr/local/apps/cogent
&& find * ! -type d|grep -v '^$'|sort -r >
/usr/local/apps/cogent/var/pkg/pillow-3.4.2
make[1]: Leaving directory
'/usr/local/src/cogent/pitchfork/ports/python/pillow'
make -j1 -C ports/python/scikit-image do-install
make[1]: Entering directory
'/usr/local/src/cogent/pitchfork/ports/python/scikit-image'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory
'/usr/local/src/cogent/pitchfork/ports/python/scikit-image'
make -j1 -C ports/python/biopython do-install
make[1]: Entering directory
'/usr/local/src/cogent/pitchfork/ports/python/biopython'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory
'/usr/local/src/cogent/pitchfork/ports/python/biopython'
make -j1 -C ports/python/bx-python do-install
make[1]: Entering directory
'/usr/local/src/cogent/pitchfork/ports/python/bx-python'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory
'/usr/local/src/cogent/pitchfork/ports/python/bx-python'
make -j1 -C ports/python/PuLP do-install
make[1]: Entering directory
'/usr/local/src/cogent/pitchfork/ports/python/PuLP'
make[1]: Nothing to be done for 'do-install'.
make[1]: Leaving directory
'/usr/local/src/cogent/pitchfork/ports/python/PuLP'
make -C ports/thirdparty/ssw_lib do-install
make[1]: Entering directory
'/usr/local/src/cogent/pitchfork/ports/thirdparty/ssw_lib'
git clone
git://github.com/mengyao/Complete-Striped-Smith-Waterman-Library
/usr/local/src/cogent/pitchfork/workspace/ssw_lib
Cloning into '/usr/local/src/cogent/pitchfork/workspace/ssw_lib'...
remote: Counting objects: 1548, done.
remote: Total 1548 (delta 0), reused 0 (delta 0), pack-reused 1548
Receiving objects: 100% (1548/1548), 12.17 MiB | 2.67 MiB/s, done.
Resolving deltas: 100% (964/964), done.
Checking connectivity... done.
Checking out files: 100% (43/43), done.
cd /usr/local/src/cogent/pitchfork/workspace/ssw_lib && git checkout
a9beb7e4c67824538e15fd781002983d2b333261
Note: checking out 'a9beb7e4c67824538e15fd781002983d2b333261'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

   git checkout -b new_branch_name

HEAD is now at a9beb7e... README updated
make -C /usr/local/src/cogent/pitchfork/workspace/ssw_lib/src CC="gcc 
-fPIC -I/usr/local/apps/cogent/include -D_GNU_SOURCE
-L/usr/local/apps/cogent/lib -L/usr/local/apps/cogent/lib64
-static-libstdc++" CXX="g++  -fPIC -I/usr/local/apps/cogent/include
-D_GNU_SOURCE  -fPIC -I/usr/local/apps/cogent/include -D_GNU_SOURCE 
-fPIC -I/usr/local/apps/cogent/include -D_GNU_SOURCE
-L/usr/local/apps/cogent/lib -L/usr/local/apps/cogent/lib64
-static-libstdc++"
make[2]: Entering directory
'/usr/local/src/cogent/pitchfork/workspace/ssw_lib/src'
gcc  -fPIC -I/usr/local/apps/cogent/include -D_GNU_SOURCE
-L/usr/local/apps/cogent/lib -L/usr/local/apps/cogent/lib64
-static-libstdc++ -c -o ssw.o ssw.c -Wall -O3 -pipe
ssw.c: In function ‘banded_sw’:
ssw.c:610:60: warning: format ‘%d’ expects argument of type ‘int’, but
argument 6 has type ‘int64_t’ {aka ‘long int’} [-Wformat=]
      fprintf(stderr, "de: %d\twidth_d: %d\treadLen: %d\ts2:%d\n", de,
width_d, readLen, s2);
~^                           ~~
                                                            %ld
gcc  -fPIC -I/usr/local/apps/cogent/include -D_GNU_SOURCE
-L/usr/local/apps/cogent/lib -L/usr/local/apps/cogent/lib64
-static-libstdc++ -o ssw_test ssw.o main.c -Wall -O3 -pipe  -lm -lz
gcc  -fPIC -I/usr/local/apps/cogent/include -D_GNU_SOURCE
-L/usr/local/apps/cogent/lib -L/usr/local/apps/cogent/lib64
-static-libstdc++ -o example_c ssw.o example.c -Wall -O3 -pipe -lm -lz
g++  -fPIC -I/usr/local/apps/cogent/include -D_GNU_SOURCE  -fPIC
-I/usr/local/apps/cogent/include -D_GNU_SOURCE  -fPIC
-I/usr/local/apps/cogent/include -D_GNU_SOURCE
-L/usr/local/apps/cogent/lib -L/usr/local/apps/cogent/lib64
-static-libstdc++ -c -o ssw_cpp.o ssw_cpp.cpp -Wall -O3 -pipe
g++  -fPIC -I/usr/local/apps/cogent/include -D_GNU_SOURCE  -fPIC
-I/usr/local/apps/cogent/include -D_GNU_SOURCE  -fPIC
-I/usr/local/apps/cogent/include -D_GNU_SOURCE
-L/usr/local/apps/cogent/lib -L/usr/local/apps/cogent/lib64
-static-libstdc++ -o example_cpp example.cpp ssw.o ssw_cpp.o -Wall -O3
-pipe  -lm -lz
gcc  -fPIC -I/usr/local/apps/cogent/include -D_GNU_SOURCE
-L/usr/local/apps/cogent/lib -L/usr/local/apps/cogent/lib64
-static-libstdc++ -Wall -O3 -pipe  -fPIC -shared -rdynamic -o libssw.so
ssw.c
ssw.c: In function ‘banded_sw’:
ssw.c:610:60: warning: format ‘%d’ expects argument of type ‘int’, but
argument 6 has type ‘int64_t’ {aka ‘long int’} [-Wformat=]
      fprintf(stderr, "de: %d\twidth_d: %d\treadLen: %d\ts2:%d\n", de,
width_d, readLen, s2);
~^                           ~~
                                                            %ld
make[2]: Leaving directory
'/usr/local/src/cogent/pitchfork/workspace/ssw_lib/src'
make[1]: Leaving directory
'/usr/local/src/cogent/pitchfork/ports/thirdparty/ssw_lib'
make -C ports/thirdparty/mash do-install
make[1]: Entering directory
'/usr/local/src/cogent/pitchfork/ports/thirdparty/mash'
/usr/local/src/cogent/pitchfork/bin/pitchfork fetch --url
https://github.com/marbl/Mash/releases/download/v1.0.2/mash-Linux64-v1.0.2.tar.gz
fetching
https://github.com/marbl/Mash/releases/download/v1.0.2/mash-Linux64-v1.0.2.tar.gz
make[1]: Leaving directory
'/usr/local/src/cogent/pitchfork/ports/thirdparty/mash'
make -C ports/pacbio/Cogent do-install
make[1]: Entering directory
'/usr/local/src/cogent/pitchfork/ports/pacbio/Cogent'
Makefile:18: *** recipe commences before first target.  Stop.
make[1]: Leaving directory
'/usr/local/src/cogent/pitchfork/ports/pacbio/Cogent'
Makefile:420: recipe for target 'Cogent' failed
make: *** [Cogent] Error 2
```

**Comment by mhsieh** [comment]
Which version of gcc are you using? I will need to reproduce it and see what I can do.

**Comment by aksenia** [comment]
`gcc version 4.9.4 (GCC)`

**Comment by mhsieh** [comment]
@aksenia your version of `make` might have been not 100% compatible with this version of pitchfork. my suggestion is to edit pitchfork/ports/pacbio/Cogent/Makefile and change
```
$(_WRKSRC):
ifeq ($(wildcard $($(_NAME)_REPO)),)
        $(GIT) clone $($(_NAME)_REPO) $@
        cd $(_WRKSRC) && $(GIT) checkout $($(_NAME)_VERSION)
DEVOPT =
else
        ln -sfn $($(_NAME)_REPO) $(_WRKSRC)
DEVOPT = -e
endif   
```
to
```
$(_WRKSRC):
        $(GIT) clone $($(_NAME)_REPO) $@
        cd $(_WRKSRC) && $(GIT) checkout $($(_NAME)_VERSION)
DEVOPT =
```
Our pitchfork will be deprecated in the near future, so I will not change the code upstream.

**Comment by Magdoll** [comment]
pitchfork is deprecated. Users should now use the [Conda/Anaconda environment](https://github.com/Magdoll/Cogent/wiki/Installing-Cogent#conda).
