### ISSUE TITLE
The final result of using Cogent to collapse redundant transcripts

### ISSUE THREAD

**Issue by ClearloveMiao** [Magdoll/Cogent#36]
Hi,

After I finish `Tutorial: Using Cogent to collapse redundant transcripts in absence of genome`, I have get a file named `hq_isoforms.fasta.no5merge.collapsed.filtered.rep.fq`, and I used `fq2fa.py` to transform it to 'hq_isoforms.fasta.no5merge.collapsed.filtered.rep.fa'.

However, in the final fasta file, the header of every sequences is like this : 
`>PB.17.1|1015_0|path0:1-3687(+)|i3_HQ_cu17009|c22037/f2p1/3705 i3_HQ_cu17009|c22037/f2p1/3705 isoform=c22037;full_length_coverage=2;non_full_length_coverage=1;isoform_length=3705`

It seems like each '|' divided the header and contains many valuable messages. But it is difficult for me to understand the message in the header, for example, what is the meaning of `path`, `f2p1` and these numbers? so can someone explain it more detailed?

Thanks a lot!

**Comment by Magdoll** [comment]
Hi @ClearloveMiao ,

New headers are added every time you go through a step. The steps you have done, in chronological order are:

1. Iso-Seq, the output header is `i3_HQ_cu17009|c22037/f2p1/3705 `. `HQ` stands for high-quality. `cu17009` is the sample name. `c22037` is the cluster ID (you can ignore this). `f2p1` means it contained 2 full-length reads and 1 non-full-length read. 3705 is the isoform length.

2. Cogent fake genome, the output header adds `1015_0|path0:1-3687(+)`. You can mostly ignore this header.

3. Post-collapse ID: `PB.17.1`. This tells you that this is on locus `PB.17` and is the first isoform of that locus.

**Comment by ClearloveMiao** [comment]
Thanks very much. I have understood it now.
