### ISSUE TITLE
Could not finish one failed job in the reconstruction step using Cogent v3.5

### ISSUE THREAD

**Issue by jayceejiao** [Magdoll/Cogent#37]
Hi  @Magdoll 

I am using Cogen 3.5 to reconstruct a coding genome for another species without a reference genome. I still have one failed job when I run reconstruct_contig.py script for one family. 
**CMD:  reconstruct_contig.py --nx_cycle_detection  .
[hello.log](https://github.com/Magdoll/Cogent/files/2092500/hello.log)

[nohup.txt](https://github.com/Magdoll/Cogent/files/2092503/nohup.txt)

**
Can you help me with this problem?

Thanks!

Chen

**Comment by Magdoll** [comment]
Hi @jayceejiao ,
Please send the input file (`in.fa`) that resulted in this error. Or provide me an email so I can request a secure data upload.

Thanks,
--Liz

**Comment by Magdoll** [comment]
Closed unless further information is provided.
