### ISSUE TITLE
Cogent analysis for isoSeq3`s result

### ISSUE THREAD

**Issue by hmyh1202** [Magdoll/Cogent#42]
What sequence should I used as intput for isoSeq3 software? If the final HQ fasta sequence or flnc fasta file?
thanks

**Comment by Magdoll** [comment]
Hi @hmyh1202 ,

Are you talking about Iso-Seq3 or Cogent? This is the Cogent repository.

For Iso-Seq3, please follow the [Iso-Seq3 tutorial](https://github.com/PacificBiosciences/IsoSeq_SA3nUP/wiki/Tutorial:-Installing-and-Running-Iso-Seq-3-using-Conda).
