### ISSUE TITLE
A running error about 'filter_away_subset.py'

### ISSUE THREAD

**Issue by ClearloveMiao** [Magdoll/Cogent#44]
Hi!
I am running `Collapsing redundant isoforms` and running `filter_away_subset.py` to collapsing isoforms using Cogent and Cupcake.

However, it has reported such error below:
`The number of PBID records in the files disagree! Sanity check failed.`
`# of PBIDs in isoforms.fasta.no5merge.collapsed.rep.fq: 42879`
`# of PBIDs in isoforms.fasta.no5merge.collapsed.gff: 42879`
`# of PBIDs in isoforms.fasta.no5merge.collapsed.abundance.txt: 0`

I have run Cogent and collapsing redundant isoforms for two times, but this time, the error it has reported make me very confused, and I really want to know the reason why it reported such error and how to do deal with it. 

So, if you have some suggestion, please tell me, thank for any suggeutions!

**Comment by ClearloveMiao** [comment]
I have used `minimap` to create the `sam` file, so is this step account for the error? Should I use `gmap`? But, `gmap` has taken on too much resources in our sever............

**Comment by Magdoll** [comment]
Hi @ClearloveMiao ,

The error indicates an error at the collapse step using `collapse_isoforms_by_sam.py`. When you ran `collapse_isoforms_by_sam.py` were there any error messages? 

Can you share the input fasta (`isoforms.fasta`) and minimap2 SAM file and the `collapse_isoforms_by_sam.py` command you used? If you provide an email I can request a secure file upload.

--Liz

**Comment by ClearloveMiao** [comment]
Hi @Magdoll 
Thanks for your reply!
Sorry, I have gone out for field work these days so I haven't reply you in time.
First, when I ran `collapse_isoforms_by_sam.py`, there are not any error messages.
Second, my email is `756243875@qq.com`.
Thanks a lot.

**Comment by Magdoll** [comment]
Hi @ClearloveMiao ,
I have sent you a request for file upload for troubleshooting.

**Comment by Magdoll** [comment]
Closed until further notice from OP.
