### ISSUE TITLE
Another error in running `process_kmer_to_graph.py`

### ISSUE THREAD

**Issue by EXGDT** [Magdoll/Cogent#45]
All my software, Cogent, minimap2, mash and so on is the latest, and python version is 2.7.13. 
I have run the test_cogent.py, and it's ok.
I firstly run the run_mash.py without error and warning. For a fasta file which have about 19,000 sequences,  an dist file about 8.5M generate was generated, which have about 15,000 lines.
Then I run the process_kmer_to_graph.py, after printing
`making weight graph from  non-redundancy.fasta.s1000k30.dist
graph contains 13289 nodes, 86287 edges
performing ncut on graph....
(subgraph) has 2 nodes. ncut down to 1 partitions in 0.00198984146118 sec`,
there are many traceback was printing, and a exception has been arisen:
`
File "/home/exgdt/.conda/envs/anaCogent/lib/python2.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 1605, in eigsh
    params.iterate()
  File "/home/exgdt/.conda/envs/anaCogent/lib/python2.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 569, in iterate
    self._raise_no_convergence()
  File "/home/exgdt/.conda/envs/anaCogent/lib/python2.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 375, in _raise_no_convergence
    raise ArpackNoConvergence(msg % (num_iter, k_ok, self.k), ev, vec)
scipy.sparse.linalg.eigen.arpack.arpack.ArpackNoConvergence: ARPACK error -1: No convergence (12011 iterations, 98/100 eigenvectors converged)
`
I see another issue mention this case, and his problem is memory is not enough. So I run the process_kmer_to_graph.py on the cluster which have 64G memory but the same error. The Cogent version on cluster is 2.1 and it has been finish many task without error. So I think maybe the error in .dist which generated by Cogent 3.5?

**Comment by EXGDT** [comment]
[non-redundancy.fasta.s1000k30.dist.txt](https://github.com/Magdoll/Cogent/files/2245684/non-redundancy.fasta.s1000k30.dist.txt)
Here is my .dist file, can someone test it?

**Comment by Magdoll** [comment]
Hi @401522126 ,

Sorry for the late response. The error comes from likely the graph cut not being able to converge. See this [page](https://docs.scipy.org/doc/scipy/reference/tutorial/arpack.html). There are several solutions proposed in that page, but I'm not able to access those parameters from scikit's graph cut code right now.

One intermediate solution is to change the ncut threshold by running
```
process_kmer_to_graph.py fake.fasta non-redundancy.fasta.s1000k30.dist.txt test test --ncut_threshold 0.1
```

And I was able to complete the graph cut. The graphs will likely be a bit smaller this way, though.

--Liz
