### ISSUE TITLE
Can not find command run_preCluster.py

### ISSUE THREAD

**Issue by huajiachicat** [Magdoll/Cogent#48]
Hello Magdoll:

I am trying to use Cogent to do family finding for large datasets and found there is no run_preCluster.py on directory (anaconda2/bin/ or anaconda2/envs/anaCogent/bin/). 

`run_preCluster.py: command not found`

I have installed all the necessary components of Cogent (minimap2 version 2.12, Cogent version 3.3). The test scripts and family finding for small dataset runs smoothly. 

These are scripts found on Cogent/Cogent/:

> all_simple_paths.py                              GFF.py                    process_kmer_to_graph.pyc  sanity_checks.pyc  splice_graph.pyc
all_simple_paths.pyc                             helper_scripts            process_path.py            settings.py        test
BioReaders.py                                    __init__.py               process_path.pyc           settings.pyc       Utils.py
BioReaders.pyc                                   __init__.pyc              reconstruct_contig.py      splice_align.py    Utils.pyc
draw_kmer_graphs.py                              MinimapIO.py              reconstruct_contig.pyc     splice_align.pyc
generate_batch_cmd_for_Cogent_family_finding.py  process_kmer.py           run_mash.py                splice_cycle.py
generate_batch_cmd_for_Cogent_reconstruction.py  process_kmer.pyc          run_mash.pyc               splice_cycle.pyc
gff3_to_collapsed.py                             process_kmer_to_graph.py  sanity_checks.py           splice_graph.py

**Comment by Magdoll** [comment]
hi @huajiachicat ,

`run_preCluster.py` is an additional script from [cDNA_Cupcake](https://github.com/Magdoll/Cogent/wiki/Installing-Cogent#cupcake). Please install Cupcake accordingly.

-Liz
