### ISSUE TITLE
mash not found error

### ISSUE THREAD

**Issue by ale07alvarez** [Magdoll/Cogent#49]
I'm running run_mash.py:
(anaCogent) xxx@xxx-xxx-xxx:~/xx/Data$ run_mash.py -k 30 --cpus=12 hq_isoforms.fasta
Error:
/bin/sh: 1: mash: not found
mash executable does not exist. Please install mash first!

**Comment by Magdoll** [comment]
Hi,
Please install mash per [tutorial requirement](https://github.com/Magdoll/Cogent/wiki/Installing-Cogent#external-software-requirement) and ensure mash is available in your environment (ex: in $PATH variable or under bin).

--Liz

**Comment by ale07alvarez** [comment]
Error in step 5 of the tutorial 
(5) Install additional libraries that we need
conda install -c http://conda.anaconda.org/timcera pulp
#-------ERROR:
 Solving environment: failed
CondaHTTPError: HTTP 404 NOT FOUND for url <http://conda.anaconda.org/timcera/noarch/repodata.json>
Elapsed: 00:00.418705
CF-RAY: 463904c2cb1976ca-LAX

The remote server could not find the noarch directory for the
requested channel with url: http://conda.anaconda.org/timcera

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.
#-------my configuration
conda config --show channels
channels:
-defaults

**Comment by Magdoll** [comment]
Please use a different package source location

`conda install -c conda-forge pulp`

I'll update the documentation.
--Liz
