### ISSUE TITLE
No module named ssw_wrap

### ISSUE THREAD

**Issue by zhangfei1947** [Magdoll/Cogent#5]
Hello! I'am trying to run Cogent, but I not sure where to find the python module "ssw_wrap". neither "ssw-0.3.1" nor "Complete-Striped-Smith-Waterman-Library-1.1" helps.

**Comment by Magdoll** [comment]
Hi,

Please follow the instructions [here](https://github.com/Magdoll/Cogent/wiki/Installing-Cogent). You will have to install the [SSW library](https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library) first and include it in your library and python path as below:

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<your_dir>/Cogent/Complete-Striped-Smith-Waterman-Library/src
export PYTHONPATH=$PYTHONPATH:<your_dir>/Cogent/Complete-Striped-Smith-Waterman-Library/src
```
