### ISSUE TITLE
run_mash.py might add format detection function

### ISSUE THREAD

**Issue by xuzhougeng** [Magdoll/Cogent#52]
I use Cogent 3.3 to learn how to use Cogent to reconstruct fake-genome. When I  wrongly use `wget https://github.com/Magdoll/Cogent/blob/master/test_data/test_human.fa` rather than `wget https://raw.githubusercontent.com/Magdoll/Cogent/master/test_data/test_human.fa` to download data, I get the html file instead of fasta.

I use this html file as input for  `run_mash.py`, so I get the follwoing error

![error](https://user-images.githubusercontent.com/19432485/47022792-d8f17a00-d190-11e8-8bf9-44f0fdd92cc3.png)

I need use `kill` to stop this process because they seem not to stop by themselves. 

After a long time debug, I find the problem was caused by the wrong input file. 

So would you like to add function to check the input format?

**Comment by Magdoll** [comment]
Hi @xuzhougeng ,
Thank you for the suggestion. I agree and will let you know when I've added sanity checks.
-Liz

**Comment by Magdoll** [comment]
Decided not to support file sanity checking at this level. Close issue.
