### ISSUE TITLE
More sequences after "Tutorial: Using Cogent to collapse redundant transcripts in absence of genome" ?

### ISSUE THREAD

**Issue by jvhaarst** [Magdoll/Cogent#57]
I think I'm doing something wrong, as I have this : 
After Iso-Seq3, I have 188238 high quality transcripts.
I ran Cogent, which gives me 46289 sequences from all the cogent2.renamed.fasta files.
I created a fake genome, adding 25079 sequences from preCluster_out.orphans.fasta, giving a total of **71368** as input for the collapsing steps.

After running through the tutorial, I end up with **102814** sequences.

So instead of ending up with less, I end up with more....

These are the line counts of all the files, as produced in the tutorial, maybe it helps:
```
    262283 hq_isoforms.fastq.sorted2.sam
    103465 hq_isoforms.fastq.2.no5merge.collapsed.abundance.txt
    102829 hq_isoforms.fastq.2.no5merge.collapsed.filtered.abundance.txt
    232548 hq_isoforms.fastq.2.no5merge.collapsed.filtered.gff
    205628 hq_isoforms.fastq.2.no5merge.collapsed.filtered.rep.fasta             102814 sequences
    411256 hq_isoforms.fastq.2.no5merge.collapsed.filtered.rep.fq                102814 sequences
    234635 hq_isoforms.fastq.2.no5merge.collapsed.gff
    238110 hq_isoforms.fastq.2.no5merge.collapsed.gff.unfuzzy
    103450 hq_isoforms.fastq.2.no5merge.collapsed.group.txt
    104837 hq_isoforms.fastq.2.no5merge.collapsed.group.txt.unfuzzy
   2186408 hq_isoforms.fastq.2.no5merge.collapsed.read_stat.txt
    413800 hq_isoforms.fastq.2.no5merge.collapsed.rep.fq                         103450 sequences
      8569 hq_isoforms.fastq.2.no5merge.ignored_ids.txt
```

**Comment by Magdoll** [comment]
Hi @jvhaarst ,

I don't see the issue here...? Your input (HQ) was 188,238 sequences. After collapse, it was 102,814 sequences. So there is a reduction.

I think you may have been confused about what the number 71,368 is. That is not collapsed transcript sequences, rather, the Cogent outputs are *reconstructed genome portions*. So, it is the 102,814 you should be looking at as unique transcript sequences.

--Liz
