### ISSUE TITLE
Error while installing 

### ISSUE THREAD

**Issue by srbehera** [Magdoll/Cogent#58]
I am getting the following error when I run this step 
> python setup.py install

```
Running matplotlib-3.0.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-HY3mQ2/matplotlib-3.0.2/egg-dist-tmp-JdxTu8
error: Setup script exited with 
Matplotlib 3.0+ does not support Python 2.x, 3.0, 3.1, 3.2, 3.3, or 3.4.
Beginning with Matplotlib 3.0, Python 3.5 and above is required.

This may be due to an out of date pip.

Make sure you have pip >= 9.0.1.
```

I have installed python 3.6, but its showing 2.7 inside the virtual environment

(anCogent) [ Cogent]$ python --version
Python 2.7.15
(anCogent) [ Cogent]$ source deactivate
[ Cogent]$ python --version
Python 3.6.7

**Comment by Magdoll** [comment]
Hi @srbehera ,

I don't think Cogent currently supports Python3. I developed all the code using Python 2.7. I'm going to guess you have some Python environment mixed up. Conda can control to use very specific Python environments. See [here](https://chris35wills.github.io/conda_python_version/).

**Comment by perez-kevin** [comment]
Same error here.
Solved here https://github.com/cocodataset/cocoapi/issues/237.
`pip install matplotlib`
