### ISSUE TITLE
Can't get "in.trimmed.fa.cogent2.gff" output file?

### ISSUE THREAD

**Issue by zhangfei1947** [Magdoll/Cogent#6]
Hello ! I can't get "in.trimmed.fa.cogent2.gff" output file using the example data while testing.

**Comment by Magdoll** [comment]
I'm looking into the test issues now. Expect some resolution in a day or two.

**Comment by Magdoll** [comment]
Hi,

By default `in.trimmed.fa.cogent2.gff` is not generated as it is not an essential part of the process. `cogent2.fa` is the output so `in.trimmed.fa.cogent2.gff` is just an additional post-Cogent alignment of the input to the output.

If you want to generate this file, you can do it manually using GMAP:

```
gmap_build -D . -d cogent2 cogent2.fa
gmap -D . -d cogent2 -f gff3_gene -n 0 -t 1 -z sense_force in.trimmed.fa > in.trimmed.fa.cogent2.gff
```

**Comment by zhangfei1947** [comment]
Thank you very much for your quick and detailed response, Liz!  ^^

**Comment by zhangfei1947** [comment]
Dear Magdoll:
    I have test the cogent with my own iso-seq data. I used the ICE output consensus reads as input, and the parameters is default 1000 and 30. But the cluster results is not very ideal, the input reads number is about 10,000 and the output is 9,000. Is this right or can I change some parameters to improve the results? thank you!

**Comment by linglingtingfei** [comment]
Hi @Magdoll ，
When I run reconstruct_contig.py, it produced a error(shown on screenshot) during additional post-Cogent alignment of the input file.
My code: `reconstruct_contig.py test_human/0 -D /zs32/data-analysis/liucy_group/llhuang/Reflib -d gmap20151231-hg19`

![qq 20170628201320](https://user-images.githubusercontent.com/20789616/27636475-55a17934-5c3e-11e7-8c38-4adf3db38b1a.jpg)

**Comment by Magdoll** [comment]
My guess is your genome is smaller than 4GB (which should call "gmap" not
"gmapl") so you should supply the `--small_genome` parameter.

To verify, you can manually run the `gmapl -D ....` command to confirm.

--Liz
