### ISSUE TITLE
gmap_build failed

### ISSUE THREAD

**Issue by MaPengyu** [Magdoll/Cogent#60]
I got an err with the command:`gmap_build -D . -d fake_genome ../cogent.fake_genome.fasta`
`Processed short contigs (<1000000 nt): ."/gmap-2018-07-04/bin/fa_coords"       -o "./fake_genome.coords" -f "./fake_genome.sources" failed with return code 6400 at /gmap-2018-07-04/bin/gmap_build line 295
`

**Comment by Magdoll** [comment]
Hi @MaPengyu ,

I'm not responsible for GMAP failures. Please contact GMAP author for problems. 

Good luck!
--Liz
