### ISSUE TITLE
Python encoding issue

### ISSUE THREAD

**Issue by goodgodric28** [Magdoll/Cogent#61]
Installed dependencies and Cogent, sourced anaCogent properly and pointed to the correct library and python paths. However, when I test the setup with `python setup.py test`, I get an encoding error: 

> SyntaxError: Non-ASCII character '\xe2' in file /home/goodheart/miniconda2/envs/anaCogent/lib/python2.7/site-packages/scipy-1.2.0-py2.7-linux-x86_64.egg/scipy/stats/_stats_mstats_common.py on line 331, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Any suggestions?

Thanks

**Comment by Magdoll** [comment]
Hi @goodgodric28 ,

Sorry but this seems to be a scipy problem and I'm not sure if it's because you have some issue with the scipy version you are using.

I just checked my Anaconda scipy version and it is `1.1.0`...maybe try downgrading to that?

```
>>> scipy.__version__
'1.1.0'
```
