### ISSUE TITLE
Trouble in run_preCluster.py

### ISSUE THREAD

**Issue by lijl459** [Magdoll/Cogent#66]
Hellow @Magdoll ,
    When I Run Family Finding for a big dataset in Cogent, I got a trouble. After finished the first step, I got a  preCluster.cluster_info.csv file and a preCluster_out. Everything seems to be right. But when I cheeked the files, I found two results were too big. In one bin, the isoseq_flnc.fasta contain 89659 sequences, which the other bin is  50232. There were 4281 bins, each bin contained less than 200 sequences except the two bins. 
    Is that the wrong results. I has 196474 sequences in total after catted the HQ and LQ sequences and cd-hit.
    Best wishes!

**Comment by lijl459** [comment]
If I add the parameter --num_seqs_per_batch 180000 is right?

**Comment by lijl459** [comment]
Hello @Magdoll

**Comment by lijl459** [comment]
Hello @Magdoll 
When I added the  parameter --num_seqs_per_batch 180000, only one bin contained the large sequences, which is 43800. Here I'd like to ask for you advice that if I can run this large file alone ?  Do you think it is appropriate to combine the final.partition.txt yield by the 43800 sequences and that yield by the 196474 sequences except the  43800 sequences ?

**Comment by Magdoll** [comment]
Hi @lijl459 ,

It's hard to say. Are you willing to share the data with me? I'll need an email address. Want to check how that big bin complexity is.

--Liz

**Comment by lijl459** [comment]
Hello @Magdoll ,
  I already shared my data to you by my gamil. Thanks! Looking forward to your reply.

**Comment by Magdoll** [comment]
Hi @lijl459 ,
Apologies for the late reply.

I tried two runs and the second one produces a smaller bin by ignoring partial hits which may suit you better:


Approach 1:
```
run_preCluster.py --cpus 30

Top cluster size: 90184, 49438, 1151, 97
```

Approach 2:
```
run_preCluster.py --cpus 30 --dun_use_partial

Top bin size: 3756, 2692, 1252, 736
```

**Comment by lijl459** [comment]
Hello @Magdoll ,
    Thank you very much! It works!
