### ISSUE TITLE
Error when running filter_away_subset.py

### ISSUE THREAD

**Issue by yiwenwang25** [Magdoll/Cogent#71]
Hi @Magdoll ,

I followed "Tutorial: Using Cogent to collapse redundant transcripts in absence of genome" to do collapse redundant isoforms. However, I got an error showed I should use a .fq file as the input when I run filter_away_subset.py (the last step of the tutorial). I've checked that there were no any .fq output files from the previous few steps, but only fasta files. I was wondering which .fq file I should use at this step.

Any suggestion would be appreciated.

Thank you,
Yi-Wen

**Comment by Magdoll** [comment]
Hi @yiwenwang25 ,

You can make a fastq file from a fasta file using `fa2fq.py` (you may have to rename the file extension from `xxx.fastq` to `xxx.fq` though).

-Liz

**Comment by yiwenwang25** [comment]
Hi @Magdoll 
It works! Thank you so much!
