### ISSUE TITLE
failed reconstruction

### ISSUE THREAD

**Issue by qiuxx221** [Magdoll/Cogent#74]
Hi, I finished the run, most reconstruction was successful. However, there is 153 failed transcripts reconstruction, are there any ways to rerun those failed ones as a batch file?

**Comment by Magdoll** [comment]
Hi @qiuxx221 ,
The failed runs usually indicate you need to go in manually and play around with the kmer size...so right now I haven't really supported failed runs with batch file. You can probably process the failed run directories and generate new commands with varying kmer sizes.

-Liz
