### ISSUE TITLE
Error because of bx-python==0.7.3

### ISSUE THREAD

**Issue by jvhaarst** [Magdoll/Cogent#76]
Hi,

Yesterday it worked with bxpython 0.7.3, but after your update it doesn't.
During compilation of bx-python gcc errors out.

Changing to the latest bxpython fixes this, but you probably put bxpython on 0.7.3 for a reason.
What will break if I use the latest version ?

**Comment by Magdoll** [comment]
What version are you using? I realize there's some confusion. There seems to be multiple packages called bx-python and [this is the one](https://anaconda.org/bcbio/bx-python) I'm referring to, which is on version 0.7.3.

--Liz

**Comment by jvhaarst** [comment]
I am using the latest version from the master branch.
All I did to get it working is remove the version pinning in the setup.py.
If you want I can check tomorrow what it actually does.

**Comment by jvhaarst** [comment]
I see you have already changed the bx-python lines both here and in Cupcake, so that solves the problems I had.
