### ISSUE TITLE
process_kmer_to_graph.py conflicts with networkx 2.4

### ISSUE THREAD

**Issue by Aprilcxy** [Magdoll/Cogent#78]
Hi, I just would like to share with all who have had the same problem when testing Cogent 6.0.0. After I have installed Cogent 6 and test if it's functional by running:
`cd <cogent_directory>
python -m unittest Cogent/test/test_cogent.py`
I received an Error message:
 ......process_kmer_to_graph.py", line 67, in family_finding
 G.node[n]['labels'] = [n]
AttributeError: 'Graph' object has no attribute 'node'

Then I replaced networkx 2.4 with networkx 2.3. The problem solved.

**Comment by Magdoll** [comment]
Thank you for the heads up. Yes, there's been changes in networkx from version to version. I'll update the documentation to reflect this...
-Liz

**Comment by mollydawson** [comment]
Hi there,

I am working on process_kmer_to_graph.py of Cogent v6.0.0 and I'm running into deprecated functions as well with networkx v2.4. I tried uninstalling networkx v2.4 to subsequently install and try v2.3, however I think conda (v4.8.4) is failing when trying to uninstall/install packages in my anaCogent environment. Below are some of the errors I receive w/ process_kmer_to_graph.py. If it's helpful I can also include the traceback errors I receive with conda remove -n anaCogent networkx.

Please let me know if there are any recommendations as to how I should proceed. Thank you for your time!

**Errors when running process_kmer_to_graph:**
making weight graph from  19CA39_MA.fasta.s1000k30_run_mash.dist
Traceback (most recent call last):
  File "/rhome/mdawson/Cogent/Cogent/process_kmer_to_graph.py", line 155, in <module>
    ncut_threshold=args.ncut_threshold)
  File "/rhome/mdawson/Cogent/Cogent/process_kmer_to_graph.py", line 67, in family_finding
    G.node[n]['labels'] = [n]
AttributeError: 'Graph' object has no attribute 'node'

making weight graph from  19CA39_MA.fasta.s1000k30_run_mash.dist
graph contains 13092 nodes, 6376559 edges
performing ncut on graph....
Traceback (most recent call last):
  File "/rhome/mdawson/Cogent/Cogent/process_kmer_to_graph_MD_mod.py", line 155, in <module>
    ncut_threshold=args.ncut_threshold)
  File "/rhome/mdawson/Cogent/Cogent/process_kmer_to_graph_MD_mod.py", line 76, in family_finding
    for g in nx.connected_component_subgraphs(G):
AttributeError: module 'networkx' has no attribute 'connected_component_subgraphs'

making weight graph from  19CA39_MA.fasta.s1000k30_run_mash.dist
graph contains 13092 nodes, 6376559 edges
performing ncut on graph....
Traceback (most recent call last):
  File "/rhome/mdawson/Cogent/Cogent/process_kmer_to_graph_MD_mod.py", line 155, in <module>
    ncut_threshold=args.ncut_threshold)

  File "/rhome/mdawson/Cogent/Cogent/process_kmer_to_graph_MD_mod.py", line 77, in family_finding
    run_ncut(g, labels2_map, ncut_map, nodelist, ncut_threshold)
  File "/rhome/mdawson/Cogent/Cogent/process_kmer_to_graph_MD_mod.py", line 17, in run_ncut
    labels = np.array([i for i in G.nodes()])
AttributeError: 'set' object has no attribute 'nodes'


(anaCogent) mdawson@parrot: conda --version
conda 4.8.4
(anaCogent) mdawson@parrot: python /rhome/Cogent/Cogent/process_kmer_to_graph.py --version
> process_kmer_to_graph.py Cogent 6.0.0
(anaCogent) mdawson@parrot: conda list -n anaCogent
# packages in environment at /rhome/mdawson/anaconda3/envs/anaCogent:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2020.07                  py37_0
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
anaconda                  custom                   py37_1
anaconda-client           1.7.2                      py_0    conda-forge
anaconda-project          0.8.3                      py_0    conda-forge
argh                      0.26.2          pyh9f0ad1d_1002    conda-forge
argon2-cffi               20.1.0           py37h8f50634_1    conda-forge
asn1crypto                1.4.0              pyh9f0ad1d_0    conda-forge
astroid                   2.4.2            py37hc8dfbb8_0    conda-forge
astropy                   4.0.1.post1      py37h8f50634_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
autopep8                  1.5.4              pyh9f0ad1d_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forg
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
beautifulsoup4            4.9.1            py37hc8dfbb8_0    conda-forge
biopython                 1.77             py37h8f50634_0    conda-forge
bitarray                  1.4.2            py37h8f50634_0    conda-forge
bkcharts                  0.2                      py37_0
blas                      1.0                         mkl
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
blosc                     1.20.0               he1b5a44_0    conda-forge
bokeh                     2.1.1            py37hc8dfbb8_0    conda-forge
boto                      2.49.0                     py_0    conda-forge
bottleneck                1.3.2            py37h03ebfcd_1    conda-forge
brotli                    1.0.7             he1b5a44_1004    conda-forge
brotlipy                  0.7.0           py37h8f50634_1000    conda-forge
brunsli                   0.1                  he1b5a44_0    conda-forge
bx-python                 0.8.9            py37h029c07a_1    bioconda
bzip2                     1.0.8                h516909a_2    conda-forge
c-ares                    1.11.0               h470a237_1    bioconda
ca-certificates           2020.6.20            hecda079_0    conda-forge
cairo                     1.16.0            hcf35c78_1003    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.1           py37h2b28604_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
charls                    2.1.0                he1b5a44_2    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.5.0                      py_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.3                      py_0    conda-forge
contextlib2               0.6.0.post1                py_0    conda-forge
cryptography              3.0              py37hb09aad4_0    conda-forge
curl                      7.71.1               he644dc0_4    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.21          py37h3340039_0    conda-forge
cytoolz                   0.10.1           py37h516909a_0    conda-forge
dask                      2.22.0                     py_0    conda-forge
dask-core                 2.22.0                     py_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
distributed               2.22.0           py37hc8dfbb8_0    conda-forge
docutils                  0.16             py37hc8dfbb8_1    conda-forge
entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fastcache                 1.1.0            py37h8f50634_1    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
flake8                    3.8.3                      py_1    conda-forge
flask                     1.1.2              pyh9f0ad1d_0    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
fribidi                   1.0.10               h516909a_0    conda-forge
fsspec                    0.8.0                      py_0    conda-forge
future                    0.18.2           py37hc8dfbb8_1    conda-forge
get_terminal_size         1.0.0                haa9412d_0
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gevent                    20.6.2           py37h8f50634_0    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
glib                      2.65.0               h6f030ca_0    conda-forge
glob2                     0.7                        py_0    conda-forge
gmp                       6.2.0                he1b5a44_2    conda-forge
gmpy2                     2.1.0b1          py37h04dde30_0    conda-forge
graphite2                 1.3.13            he1b5a44_1001    conda-forge
greenlet                  0.4.16           py37h8f50634_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
h5py                      2.10.0          nompi_py37h90cd8ad_104    conda-forge
harfbuzz                  2.4.0                h9f30f68_3    conda-forge
hdf5                      1.10.6          nompi_h3c11f04_101    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagecodecs               2020.5.30        py37hda6ee5b_2    conda-forge
imageio                   2.9.0                      py_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        1.7.0            py37hc8dfbb8_0    conda-forge
importlib_metadata        1.7.0                         0    conda-forge
iniconfig                 1.0.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2020.1                      217
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 5.3.4            py37h43977f1_0    conda-forge
ipython                   7.17.0           py37hc6149b9_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
isort                     4.3.21           py37hc8dfbb8_1    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jbig                      2.1               h516909a_2002    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.17.1           py37hc8dfbb8_0    conda-forge

jeepney                   0.4.3                      py_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.16.0                     py_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
json5                     0.9.4              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.6                      py_0    conda-forge
jupyter_console           6.1.0                      py_1    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
jupyterlab                2.2.2                      py_0    conda-forge
jupyterlab_server         1.2.0                      py_0    conda-forge
jxrlib                    1.1                  h516909a_2    conda-forge
keyring                   21.3.0           py37hc8dfbb8_0    conda-forge
kiwisolver                1.2.0            py37h99015e2_0    conda-forge
krb5                      1.17.1               hfafb76e_2    conda-forge
lazy-object-proxy         1.4.3            py37h8f50634_2    conda-forge
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.34                 hc38a660_9    conda-forge
lerc                      2.2                  he1b5a44_0    conda-forge
libaec                    1.0.4                he1b5a44_1    conda-forge
libarchive                3.3.3             h3a8160c_1008    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libcurl                   7.71.1               hcdd3856_4    conda-forge
libedit                   3.1.20191231         h46ee950_1    conda-forge
libev                     4.33                 h516909a_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h24d8f2e_14    conda-forge
libgfortran-ng            7.5.0               hdf63c60_14    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblief                   0.10.1               he1b5a44_0    conda-forge
libllvm9                  9.0.1                he513fc3_1    conda-forge
libnghttp2                1.41.0               hab1572f_1    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libsodium                 1.0.18               h516909a_0    conda-forge
libspatialindex           1.9.3                he1b5a44_3    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               hdf63c60_14    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libtool                   2.4.6             h14c3975_1002    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
libxslt                   1.1.33               h31b3aaa_0    conda-forge
libzopfli                 1.0.3                he1b5a44_0    conda-forge
llvm-openmp               10.0.1               hc9558a2_0    conda-forge
llvmlite                  0.33.0           py37h5202443_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.5.2            py37he3881c9_0    conda-forge
lz4-c                     1.9.2                he1b5a44_1    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
markupsafe                1.1.1            py37h8f50634_1    conda-forge
matplotlib                3.3.0                         1    conda-forge
matplotlib-base           3.3.0            py37hd478181_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py37h8f50634_1001    conda-forge
mkl                       2020.2                      256    conda-forge
mkl-service               2.3.0            py37he904b0f_0
mkl_fft                   1.1.0            py37h23d657b_0
mkl_random                1.1.1            py37h0da4684_0    conda-forge
mock                      4.0.2            py37hc8dfbb8_0    conda-forge
more-itertools            8.4.0                      py_0    conda-forge
mpc                       1.1.0             h04dde30_1009    conda-forge
mpfr                      4.0.2                he80fd80_1    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
msgpack-python            1.0.0            py37h99015e2_1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
nbconvert                 5.6.1            py37hc8dfbb8_1    conda-forge
nbformat                  5.0.7                      py_0    conda-forge
ncurses                   6.2                  he1b5a44_1    conda-forge
networkx                  2.4                        py_1    conda-forge
nltk                      3.4.4                      py_0    conda-forge
nose                      1.3.7           py37hc8dfbb8_1004    conda-forge
notebook                  6.1.1            py37hc8dfbb8_0    conda-forge
nspr                      4.27                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numba                     0.50.1           py37h0da4684_1    conda-forge
numexpr                   2.7.1            py37h0da4684_1    conda-forge
numpy                     1.19.1           py37hbc911f0_0
numpy-base                1.19.1           py37hfa32c7d_0
numpydoc                  1.1.0              pyh9f0ad1d_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openpyxl                  3.0.4                      py_0    conda-forge
openssl                   1.1.1g               h516909a_1    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.1.0            py37h3340039_0    conda-forge
pandoc                    2.10.1               h516909a_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.42.4               h7062337_4    conda-forge
parasail-python           1.2              py37h13b99d1_2    bioconda
parso                     0.7.0                      py_0
partd                     1.1.0                      py_0    conda-forge
patchelf                  0.11                 he1b5a44_0    conda-forge
path                      15.0.0           py37hc8dfbb8_0    conda-forge
path.py                   12.5.0                        0    conda-forge
pathlib2                  2.3.5            py37hc8dfbb8_1    conda-forge
pathtools                 0.1.2                      py_1    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
pillow                    7.2.0            py37h718be6c_1    conda-forge
pip                       20.2.1                     py_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
pluggy                    0.13.1           py37hc8dfbb8_2    conda-forge
ply                       3.11                       py_1    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.5                      py_1    conda-forge
prompt_toolkit            3.0.5                         1    conda-forge
psutil                    5.7.2            py37h8f50634_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pulp                      1.6.8                 py37_1000    conda-forge
py                        1.9.0              pyh9f0ad1d_0    conda-forge
py-lief                   0.10.1           py37h3340039_0    conda-forge
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pycosat                   0.6.3           py37h8f50634_1004    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pycrypto                  2.6.1           py37h8f50634_1004    conda-forge
pycurl                    7.43.0.5         py37hce7685b_2    conda-forge
pydocstyle                5.0.2                      py_0    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pylint                    2.5.3            py37hc8dfbb8_0    conda-forge
pyodbc                    4.0.30           py37he1b5a44_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py37h8685d9f_3    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.16.0           py37h8f50634_0    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
pytables                  3.6.1            py37h56451d4_2    conda-forge
pytest                    6.0.1            py37hc8dfbb8_0    conda-forge
python                    3.7.8           h6f2ec95_1_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-jsonrpc-server     0.3.4              pyh9f0ad1d_1    conda-forge
python-language-server    0.34.1           py37hc8dfbb8_0    conda-forge
python-libarchive-c       2.9                      py37_0    conda-forge
python-lzo                1.12            py37h81344f2_1001    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pywavelets                1.1.1            py37h03ebfcd_1    conda-forge
pyxdg                     0.26                       py_0    conda-forge
pyyaml                    5.3.1            py37h8f50634_0    conda-forge
pyzmq                     19.0.2           py37hac76be4_0    conda-forge
qdarkstyle                2.8.1              pyh9f0ad1d_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
qtawesome                 0.7.2              pyh9f0ad1d_0    conda-forge
qtconsole                 4.7.5              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
regex                     2020.7.14        py37h8f50634_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
ripgrep                   12.1.1               h516909a_0    conda-forge
rope                      0.17.0             pyh9f0ad1d_0    conda-forge
rtree                     0.9.4            py37h8526d28_1    conda-forge
ruamel_yaml               0.15.80         py37h8f50634_1001    conda-forge
scikit-image              0.17.2           py37h0da4684_1    conda-forge
scikit-learn              0.23.1           py37h423224d_0
scipy                     1.5.0            py37h0b6359f_0
seaborn                   0.10.1                        1    conda-forge
seaborn-base              0.10.1                     py_1    conda-forge
secretstorage             3.1.2            py37hc8dfbb8_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.2.1           py37hc8dfbb8_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.4.0.3               py37_1000    conda-forge
sip                       4.19.23          py37h3340039_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sortedcollections         1.2.1              pyh9f0ad1d_0    conda-forge
sortedcontainers          2.2.2              pyh9f0ad1d_0    conda-forge
soupsieve                 2.0.1            py37hc8dfbb8_0    conda-forge
sphinx                    3.1.2                      py_0    conda-forge
sphinxcontrib             1.0                      py37_1
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
sphinxcontrib-websupport  1.2.3              pyh9f0ad1d_0    conda-forge
spyder                    4.1.4            py37hc8dfbb8_0    conda-forge
spyder-kernels            1.9.3            py37hc8dfbb8_0    conda-forge
sqlalchemy                1.3.18           py37h8f50634_0    conda-forge
sqlite                    3.32.3               hcee41ef_1    conda-forge
statsmodels               0.11.1           py37h8f50634_2    conda-forge
sympy                     1.6.1            py37hc8dfbb8_0    conda-forge
tbb                       2020.1               hc9558a2_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.8.3            py37hc8dfbb8_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tifffile                  2020.7.24                  py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toml                      0.10.1             pyh9f0ad1d_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.4            py37h8f50634_1    conda-forge
tqdm                      4.48.2             pyh9f0ad1d_0    conda-forge
traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
typed-ast                 1.4.1            py37h516909a_0    conda-forge
typing_extensions         3.7.4.2                    py_0    conda-forge
ujson                     1.35            py37h3340039_1002    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
unixodbc                  2.3.7             hd1b7508_1000    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
watchdog                  0.10.3           py37hc8dfbb8_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  1.0.1              pyh9f0ad1d_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
widgetsnbextension        3.5.1            py37hc8dfbb8_1    conda-forge
wrapt                     1.11.2           py37h8f50634_0    conda-forge
wurlitzer                 2.0.0            py37hc8dfbb8_1    conda-forge
xlrd                      1.2.0              pyh9f0ad1d_1    conda-forge
xlsxwriter                1.3.1              pyh9f0ad1d_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.10               h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
yapf                      0.30.0             pyh9f0ad1d_0    conda-forge
zeromq                    4.3.2                he1b5a44_3    conda-forge
zfp                       0.5.5                he1b5a44_1    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zope                      1.0                      py37_1
zope.event                4.4                pyh9f0ad1d_0    conda-forge
zope.interface            5.1.0            py37h8f50634_0    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge

**Comment by mollydawson** [comment]
Hi there,

I am working on process_kmer_to_graph.py of Cogent v6.0.0 and I'm running into deprecated functions as well with networkx v2.4. I tried uninstalling networkx v2.4 to subsequently install and try v2.3, however I think conda (v4.8.4) is failing when trying to uninstall/install packages in my anaCogent environment. Below are some of the errors I receive w/ process_kmer_to_graph.py. If it's helpful I can also include the traceback errors I receive with conda remove -n anaCogent networkx.

Please let me know if there are any recommendations as to how I should proceed. Thank you for your time!

**Errors when running process_kmer_to_graph:**
making weight graph from  19CA39_MA.fasta.s1000k30_run_mash.dist
Traceback (most recent call last):
  File "/rhome/mdawson/Cogent/Cogent/process_kmer_to_graph.py", line 155, in <module>
    ncut_threshold=args.ncut_threshold)
  File "/rhome/mdawson/Cogent/Cogent/process_kmer_to_graph.py", line 67, in family_finding
    G.node[n]['labels'] = [n]
AttributeError: 'Graph' object has no attribute 'node'

making weight graph from  19CA39_MA.fasta.s1000k30_run_mash.dist
graph contains 13092 nodes, 6376559 edges
performing ncut on graph....
Traceback (most recent call last):
  File "/rhome/mdawson/Cogent/Cogent/process_kmer_to_graph_MD_mod.py", line 155, in <module>
    ncut_threshold=args.ncut_threshold)
  File "/rhome/mdawson/Cogent/Cogent/process_kmer_to_graph_MD_mod.py", line 76, in family_finding
    for g in nx.connected_component_subgraphs(G):
AttributeError: module 'networkx' has no attribute 'connected_component_subgraphs'

making weight graph from  19CA39_MA.fasta.s1000k30_run_mash.dist
graph contains 13092 nodes, 6376559 edges
performing ncut on graph....
Traceback (most recent call last):
  File "/rhome/mdawson/Cogent/Cogent/process_kmer_to_graph_MD_mod.py", line 155, in <module>
    ncut_threshold=args.ncut_threshold)

  File "/rhome/mdawson/Cogent/Cogent/process_kmer_to_graph_MD_mod.py", line 77, in family_finding
    run_ncut(g, labels2_map, ncut_map, nodelist, ncut_threshold)
  File "/rhome/mdawson/Cogent/Cogent/process_kmer_to_graph_MD_mod.py", line 17, in run_ncut
    labels = np.array([i for i in G.nodes()])
AttributeError: 'set' object has no attribute 'nodes'

**Comment by mollydawson** [comment]
Please ignore above comment. I found a workaround to changing version numbers by creating a .yml file & v2.3 worked just fine. Thanks!
