### ISSUE TITLE
Can't update conda

### ISSUE THREAD

**Issue by linglingtingfei** [Magdoll/Cogent#8]
Hi Liz,
Accoring to the WiKi said, conda is installed. When i updated it, it output errors (screenshot at below). I googled it, but i still can't find a solution. Could you give me a help, please! I'd really appreciated that! Moreover, when i run the command `conda create -n anaCogent python=2.7 anaconda`, it produced the same SystemError: error return without exception set.
 
![image](https://user-images.githubusercontent.com/20789616/27508025-81520198-590f-11e7-9c7d-36483c646015.png)

**Comment by Magdoll** [comment]
Hi,
I'm not a conda/anaconda expert, but according to [this](https://github.com/conda/conda/issues/1414), you probably should have done 'conda update anaconda' instead.

In the worst case, installing a clean anaconda after wiping out the old one is probably not a bad idea.

--Liz

**Comment by linglingtingfei** [comment]
@Magdoll Thank you for your reply. I solved it. it's just a bug for  Python2.7. It's been fixed for Python3
