### ISSUE TITLE
mash not found while running tests

### ISSUE THREAD

**Issue by Luisitox** [Magdoll/Cogent#87]
Hi, I'm trying to install cogent in my cluster and I keep having an issue with mash in the testing step.

I created an alias for mash as it is suggested and if I run it in the environment it is found:

```
(anaCogent) [luisdh@access Cogent]$ mash

Mash version 2.1.1

Type 'mash --license' for license and copyright information.

Usage:

  mash <command> [options] [arguments ...]

...
```

But when I do the tests (both of them) it says that mash is not installed:

```
(anaCogent) [luisdh@access test_data]$ run_mash.py test_human.fa
/bin/sh: mash: command not found
mash executable does not exist. Please install mash first!
```

Can you help me?

Thanks,

Luis

**Comment by Magdoll** [comment]
Hi @Luisitox ,
Can you try adding mash to your `$PATH` variable?

`export PATH=$PATH:<path_to_mash>`

**Comment by Luisitox** [comment]
Hi @Magdoll,

Thanks, that worked like a charm
