### ISSUE TITLE
process_kmer_to_graph.py error: (subgraph) has 11 nodes. ncut down to 3 partitions

### ISSUE THREAD

**Issue by 52teth** [Magdoll/Cogent#9]
Hi all,
Now I have been running cogent with my isoseq  polished data (388,024 reads)  following  the wiki  instructions (https://github.com/Magdoll/Cogent/wiki/Running-Cogent).  In the step 'Family Finding', I have got the k-mer profile and generated  pairwise distances file(isoforms.fasta.s1000k30.dist). But when process the distance file and create the partitions using command: 
_process_kmer_to_graph.py  -c isoform.weights isoforms.fasta isoforms.fasta.s1000k30.dist test_
the following error comes out:
**(subgraph) has 11 nodes. ncut down to 3 partitions in 12.9096560478 sec.**
Then my progress stopped.
How would this happen? Is there any error in my data or command? 
What can I do with this error?
Thanks a lot for any reply!

**Comment by 52teth** [comment]
I rerun my job again and I find my job is killed because of memory insufficient. Now I want to know is there any required memor, cpu and time stastics for Cogent?

**Comment by Magdoll** [comment]
It really depends on the size of the input, but I usually run it with at least 60GB mem and do not see memory insufficient issues. Runtime also highly depends on input size & number CPUs you use. I'll keep in mind to generate a runtime report for Cogent when I have time.

**Comment by 52teth** [comment]
Thanks a lot for you help! I will have a try again!
