### ISSUE TITLE
Error for reconstruct_contig.py

### ISSUE THREAD

**Issue by zhuqianhua** [Magdoll/Cogent#95]
I was running Cogent on the test data as described by WIKI, steps as follows:
cd <cogent_directory>/test_data
run_mash.py test_human.fa 
process_kmer_to_graph.py -c test_human.weights test_human.fa \
   test_human.fa.s1000k30.dist test_human test_human
reconstruct_contig.py test_human/test_human_0

However, for the last step reconstruct_contig.py, it throws an error:
/ifswh1/BC_RD/RD_COM/USER/xielu/software/bioconda/soft_anzhuang/lib/python3.7/site-packages/PuLP-2.4-py3.7.egg/pulp/pulp.py:1199: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")
Traceback (most recent call last):
  File "/ifswh1/BC_RD/RD_COM/USER/xielu/software/bioconda/soft_anzhuang/lib/python3.7/site-packages/Cogent-8.0.0-py3.7.egg/Cogent/process_path.py", line 132, in solve_with_lp_and_reduce
    prob.solve()
  File "/ifswh1/BC_RD/RD_COM/USER/xielu/software/bioconda/soft_anzhuang/lib/python3.7/site-packages/PuLP-2.4-py3.7.egg/pulp/pulp.py", line 1737, in solve
    status = solver.actualSolve(self, **kwargs)
AttributeError: 'NoneType' object has no attribute 'actualSolve'

I don’t know if this is caused by my environmental variable or other reasons, coule you help me solve it?

**Comment by defendant602** [comment]
Hello， @zhuqianhua ,  did you solve your problem? I run into the same error with you ...

**Comment by zhuqianhua** [comment]
> Hello， @zhuqianhua , did you solve your problem? I run into the same error with you ...

I had updated the PuLP package, and it worked.
