### ISSUE TITLE
When run collapse_isoforms_by_sam.py,it told me No valid records from my sorted.sam file

### ISSUE THREAD

**Issue by wonitawowowo** [Magdoll/Cogent#97]
When I run Cogent as the Working with unmapped or badly-mapped Iso-Seq transcripts only ：
----------------------------------------------------------------------------------------------------------------------------------------------
minimap2 -ax splice -t 30 -uf --secondary=no Ai.ragtag.chr.fasta SRR10488719_subreads.fa > SRR10488719.fasta.sam

sort -k 3,3 -k 4,4n SRR10488719.fasta.sam > SRR10488719.fasta.sorted.sam

collapse_isoforms_by_sam.py --input SRR10488719_subreads.fa -s SRR10488719.fasta.sorted.sam \
    -c 0.99 -i 0.95 -o SRR10488719.5merge
----------------------------------------------------------------------------------------------------------------------------------------------
Then I got:
----------------------------------------------------------------------------------------------------------------------------------------------
No valid records from SRR10488719.fasta.sorted.sam!
ERROR:Sanity checking SRR10488719.5merge.collapsed.gff is GFF3 format: expected 9 tab-delimited fields but saw 1! Abort!
----------------------------------------------------------------------------------------------------------------------------------------------
And I check my .sorted.sam file:
----------------------------------------------------------------------------------------------------------------------------------------------
@SRR10488719.1  4       *       0       0       *       *       0       0       ATCTCTTCTAACCTGTCAAACAACAACCTCTAGCACCTGACCCGTCTGTCGCACGAGTACAGTTAGTAACGAGTAGGGTGTGAATGCGGTCTGTCGCGTCCGTCAACACCAACTCAAAACATTAGAAGAGAAAATAGAGG *
@SRR10488719.10 4       *       0       0       *       *       0       0       AGCAGTGGTATCAGACGCAGAGTAAGGGGGGGGAACAAGCACCTTGGAGAGCGCAGTACAACGGAGAGTGGATGTGCGTTCGGAAGGATGAATCGCCCCGAAAAGGAATCCATTGATTCTCTCCCATTGTTGACCGGAGGTGCGTGATTACTTCACGGGCGAGGTCTCTGGTTCAAATCCAGGATGGCCCAGCTGGCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGTACTCTGCGTTGATACCACTGCTT      *
@SRR10488719.100        4       *       0       0       *       *       0       0       AAGTCTTGTTTCAACGCGAGTACTGGGGGGGTAACAGCCATCTTGGAGAGGCGCAGTACAACGGAGAGTTGATGCCTTGCGTTCGGGAAGGATAATCGGGGGAGAAAGAAAAGGAATCCTTGATCTCTCCCAATTGTTGGACTCGTAGGGGGCGATGATTTACTTCACGGCGGTCCTCTGTTCAAATCCAGGATGGCCCAGCTGCGCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGTACTCTGCGTTGATACCACTGCTT       *
@SRR10488719.1000002    4       *       0       0       *       *       0       0       AAGCAGTGTATCAACGCGATTACATTGGTGAGAATTCCTTTGCAACAGAAGTTAGCCGAGGAGCCGATTCGTGCCAGCCCCTTCGAATTGAGTGCCACACGTAGGAAGAACGGTGTTCTGTCCTAAGAAGGAGCCGCGCCTTTTCGAAGCACTTTCTAGTGTGCTTTGCGCTTAGTTTGATTGCAGCTAGGCGCGCTTTACTTAATAACATAAACAACGAAATCGAAAGGTTCTCGCTTGTTTAGTTATTGTCAGTTGGCCTTATCTTGCAGAGTTACGACGACTCGCGGTGTGGTGGTGGTCGGCGGGATAAATAGGCGTGCGTCTATTCAGGCGAGTCCGCCCGGTTGGTGTACGTATGTGTTAGTACGGCCCCGCCAAAACA *
@SRR10488719.1000004    4       *       0       0       *       *       0       0       AGCAGGGTATCAACGCAGAGTACATGGGGGAGAAAGCTTTGGGGGGGGGGGGGCAACCGAAGTAGCCGAGACCAGTGACGTGCCAGCCCTTCGAATTGAGTGCCCAGCAGCGGTGTAGCTGTTGTGCTGTCGTAAGAAGTGTGTCCGGCGCCTTTCGAACATGGTCTAGTGTGCTTTGCGCTTTAGTTTTGATTGCAGCGAGCGAGCTTACTAATAAACATAAACACGAAAGCGAAAGTTGCGCGCGGTGTTAGTAAAGGTCCAGTTTTTGGCCTATCTGTCAGTACGGACTACGTCGGAGTTGGCTGGGCGGAACGACCTCGGCATTCAGCGAGCCGCCCGTGGTGTGTTACGTAGTGGTTTAGTACCCCGCAAACA        *
---------------------------------------------------------------------------------------------------------------------------------------------
Could help me solve this problem?Thanks a lot.

**Comment by Magdoll** [comment]
Hi @wonitawowowo ,

This SAM file indicates nothing is mapped.
-Liz

**Comment by wonitawowowo** [comment]
Hi @Magdoll ，Thanks for your reminding，
I find there are many sequences can’t map to my azadirachta indica genome just as：
----------------------------------------------------------------------------------------------------------------------------------------------
kangzong@gpz:~/ncbi/public/sra$ grep -e '@SRR10488719.5449800' SRR10488719.fasta.sorted.sam
@SRR10488719.5449800    4       *       0       0       *       *       0       0       AAGCATTGTATCACGCATAGTACAGGTGGGATATCTCGGCTCTCGCATCGTATGAAGAACGTAGGCGAATGCGATACTTGGTGTGAATTGCAGAATCCGTGAACCATCGAGTCTTTGACGCAAGTTTGTGGCCCAAGCCATCGGCCGAGGCACGTCGCCTGGTGTCACGCATCGTTGCCCCCCCGCACACAAAACCCCCCCAGGGGAAGTGTCGGGGAGGCGGGCGGGACTGGGCCTCGCCGTGCGCTGCCCTCTCGCGGTTGGCCAAATCCGATGCTTCGGCGACCGAGCCGGCGACGATCGGTGGTGAGACAAGCTCTCGAGCCTCCATCCTCGCGCCCAGTGCGTCCCGTGTCAGGGACTCGCGGACCCTGCACGCCCTCTGGGCTATGCTCGCTTCCGCCGACCCCAGGTGCAGTCGGACTACCCCTGAGTTTAAGCATATCAAAAAAAAAAAAAAAAAAAAACCAAAAGTACTCTCGTTTGATACACTGCTT      *
----------------------------------------------------------------------------------------------------------------------------------------------
But there are still some sequences could:
----------------------------------------------------------------------------------------------------------------------------------------------
grep -e '@SRR10488719.54498\s' SRR10488719.fasta.sorted.sam
@SRR10488719.54498      0       Chr02   13939317        60      59S25M1I5M2I23M1I42M1D12M1D4M2I9M1D7M1D12M1D29M1I19M1I43M1I3M1I3M1D13M1D2M1D18M1D11M1D21M1D37M1I14M1D3M1I38M1D38M2D2M1D14M1I5M1I32M2D14M1D1M1D4M1D3M1D36M1D9M1I29M1D8M1D46M6I10M1D13M1I13M1D13M1D11M1D42M1I3M1D4M1D31M1I16M1D7M1D12M1I14M31S *       0       0       ACAGTGGTTCACGCAGAGTACTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTCTTTAGACATTATTATTTGGCCAAATTTTATGTTCAGTTTTTTAGTAATTTCACATCGAGTTGCAACAGCGACACTCCGTTTATTCTATTACCAAATGATAAGCCTATTGATTATTCGTTGGAAACTCTATCGCCATTTTGTAGCATGACGACTCCATGCATGCATTATTACACCCTCCATTTTCTGCCTGATCAGGCGCAAAATCTTCGTCAGCCTTGATGAACACGACGGGGACCTGGTGCGCAACTTCAAGCCAGACGCCGTCTCATTCTTATCGGTATGACAGAGACGTCCCGCACAAATGGACACAAGACTCCACACCCTAGGACAGTGAACGATCCTGTAGAACACACTTTTCTGTTCCCCTCTCTGCAAACTTAAACCAGTGCATTAATGTTCGAGCTCCAGGATTCCCTTAACTCCGTTAGTAGATATGTACCACTGCCCGTGGTCGGCGTAGTCGTCCAACTGCTCCACACCGACGGATGGTTGCATGTTAATGGCGGTGGTGAACTGGTTTCAATCGCGGAGGAATAGACGAGGTGGTCATTACTGTTGGCAGTGAAAATGTTTACAGGGCGACCCTTGTTTAAATCAGAATTTCTTGGTAACGTCAAGTTGGCATGTTTTGTGTCGACCGGCGGATAAGTTAAGGGAAAAACCCCCGCCGCGTCACCGGTGATGTGCGGACACGATGAGTAATTGGTATCGTGCGGAGGGGTCGCCATTGATGTCGACCACCGGCTCAGTGGCGGCAGAGGCGTGCGAGGCAAGCGAAGGAAGGATAATGCAAGTAGTGAGCTTCTTCAGTGTTGTGTATTGGCTTGATTTAGAAGTCTTTGGTGTTTGATGTCCCCTGGTCTCTGCGTTGATACCACTGGCTT       *       NM:i:76 ms:i:613        AS:i:613        nn:i:0       ts:A:+  tp:A:P  cm:i:64 s1:i:390        s2:i:40 de:f:0.0768
----------------------------------------------------------------------------------------------------------------------------------------------
Should remove those sequences which could not map and try again?

**Comment by wonitawowowo** [comment]
Hi @Magdoll ，Thanks for your reminding，
I find there are many sequences can’t map to my azadirachta indica genome just as：
----------------------------------------------------------------------------------------------------------------------------------------------
kangzong@gpz:~/ncbi/public/sra$ grep -e '@SRR10488719.5449800' SRR10488719.fasta.sorted.sam
@SRR10488719.5449800    4       *       0       0       *       *       0       0       AAGCATTGTATCACGCATAGTACAGGTGGGATATCTCGGCTCTCGCATCGTATGAAGAACGTAGGCGAATGCGATACTTGGTGTGAATTGCAGAATCCGTGAACCATCGAGTCTTTGACGCAAGTTTGTGGCCCAAGCCATCGGCCGAGGCACGTCGCCTGGTGTCACGCATCGTTGCCCCCCCGCACACAAAACCCCCCCAGGGGAAGTGTCGGGGAGGCGGGCGGGACTGGGCCTCGCCGTGCGCTGCCCTCTCGCGGTTGGCCAAATCCGATGCTTCGGCGACCGAGCCGGCGACGATCGGTGGTGAGACAAGCTCTCGAGCCTCCATCCTCGCGCCCAGTGCGTCCCGTGTCAGGGACTCGCGGACCCTGCACGCCCTCTGGGCTATGCTCGCTTCCGCCGACCCCAGGTGCAGTCGGACTACCCCTGAGTTTAAGCATATCAAAAAAAAAAAAAAAAAAAAACCAAAAGTACTCTCGTTTGATACACTGCTT      *
----------------------------------------------------------------------------------------------------------------------------------------------
But there are still some sequences could:
----------------------------------------------------------------------------------------------------------------------------------------------
grep -e '@SRR10488719.54498\s' SRR10488719.fasta.sorted.sam
@SRR10488719.54498      0       Chr02   13939317        60      59S25M1I5M2I23M1I42M1D12M1D4M2I9M1D7M1D12M1D29M1I19M1I43M1I3M1I3M1D13M1D2M1D18M1D11M1D21M1D37M1I14M1D3M1I38M1D38M2D2M1D14M1I5M1I32M2D14M1D1M1D4M1D3M1D36M1D9M1I29M1D8M1D46M6I10M1D13M1I13M1D13M1D11M1D42M1I3M1D4M1D31M1I16M1D7M1D12M1I14M31S *       0       0       ACAGTGGTTCACGCAGAGTACTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTCTTTAGACATTATTATTTGGCCAAATTTTATGTTCAGTTTTTTAGTAATTTCACATCGAGTTGCAACAGCGACACTCCGTTTATTCTATTACCAAATGATAAGCCTATTGATTATTCGTTGGAAACTCTATCGCCATTTTGTAGCATGACGACTCCATGCATGCATTATTACACCCTCCATTTTCTGCCTGATCAGGCGCAAAATCTTCGTCAGCCTTGATGAACACGACGGGGACCTGGTGCGCAACTTCAAGCCAGACGCCGTCTCATTCTTATCGGTATGACAGAGACGTCCCGCACAAATGGACACAAGACTCCACACCCTAGGACAGTGAACGATCCTGTAGAACACACTTTTCTGTTCCCCTCTCTGCAAACTTAAACCAGTGCATTAATGTTCGAGCTCCAGGATTCCCTTAACTCCGTTAGTAGATATGTACCACTGCCCGTGGTCGGCGTAGTCGTCCAACTGCTCCACACCGACGGATGGTTGCATGTTAATGGCGGTGGTGAACTGGTTTCAATCGCGGAGGAATAGACGAGGTGGTCATTACTGTTGGCAGTGAAAATGTTTACAGGGCGACCCTTGTTTAAATCAGAATTTCTTGGTAACGTCAAGTTGGCATGTTTTGTGTCGACCGGCGGATAAGTTAAGGGAAAAACCCCCGCCGCGTCACCGGTGATGTGCGGACACGATGAGTAATTGGTATCGTGCGGAGGGGTCGCCATTGATGTCGACCACCGGCTCAGTGGCGGCAGAGGCGTGCGAGGCAAGCGAAGGAAGGATAATGCAAGTAGTGAGCTTCTTCAGTGTTGTGTATTGGCTTGATTTAGAAGTCTTTGGTGTTTGATGTCCCCTGGTCTCTGCGTTGATACCACTGGCTT       *       NM:i:76 ms:i:613        AS:i:613        nn:i:0       ts:A:+  tp:A:P  cm:i:64 s1:i:390        s2:i:40 de:f:0.0768
----------------------------------------------------------------------------------------------------------------------------------------------
Should remove those sequences which could not map and try again?

**Comment by wonitawowowo** [comment]
I find it's beacuse the '@' before the sequeces ID which I didn't remove when convert the fastq file to fasta.When I  delete the ‘@’，it works well.
